import { useState, useMemo } from 'react';
import { Settings, Play, Plus, Trash2, ShieldCheck, UserCheck, Info, Check, GitCommit, LayoutGrid, FileText } from 'lucide-react';
import { type Automaton, type Transition, EPSILON } from './lib/types.ts';
import { GraphView } from './components/GraphView';
import { TransitionTable } from './components/TransitionTable';
import { tokenize } from './lib/regex/lexer.ts';
import { Parser } from './lib/regex/parser.ts';
import { compileASTToENFA } from './lib/core/thompson.ts';
import { eliminateEpsilon } from './lib/core/epsilonElimination.ts';
import { compileToDFA } from './lib/core/subsetConstruction.ts';
import { minimizeDFA } from './lib/core/minimization.ts';
import { generateRegex } from './lib/core/stateElimination.ts';
import { validateAutomaton } from './lib/validator.ts';
import {
  applyAddState,
  applyDeleteState,
  applyRenameState,
  applyAddTransition,
  applyDeleteTransition,
  applySetStartState,
  applyToggleAcceptState
} from './lib/core/canvasAdapters.ts';
import { simulateDFA, simulateNFA, simulateENFA } from './lib/core/simulator.ts';
import {
  type WorkspaceItem,
  generateUUID,
  addRegexToWorkspace,
  compileRegexInWorkspace,
  eliminateEpsilonInWorkspace,
  subsetConstructionInWorkspace,
  minimizeInWorkspace,
  generateRegexInWorkspace,
  compareWorkspaceItems
} from './lib/core/workspace.ts';
import './index.css';

type Tab = 'CONVERTER' | 'EDITOR' | 'WORKSPACE';
type Mode = 'RE_TO_NFA' | 'NFA_TO_DFA' | 'DFA_TO_RE';

function App() {
  // Navigation State
  const [activeTab, setActiveTab] = useState<Tab>('CONVERTER');

  // View Toggle States
  const [editorViewMode, setEditorViewMode] = useState<'graph' | 'table'>('graph');
  const [workspaceViewMode, setWorkspaceViewMode] = useState<'graph' | 'table'>('graph');

  // ==========================================
  // 1. REGEX CONVERTER STATE & LOGIC
  // ==========================================
  const [regexInput, setRegexInput] = useState('(a|b)*abb');
  const [mode, setMode] = useState<Mode>('RE_TO_NFA');
  const [converterError, setConverterError] = useState<string | null>(null);

  const conversionData = useMemo(() => {
    try {
      if (!regexInput) return null;
      setConverterError(null);
      
      const tokens = tokenize(regexInput);
      const parser = new Parser(tokens);
      const ast = parser.parse();
      const enfa = compileASTToENFA(ast);
      const nfa = eliminateEpsilon(enfa);
      const dfa = compileToDFA(nfa);
      const minDfa = minimizeDFA(dfa);
      const finalRe = generateRegex(minDfa);
      
      return {
        enfa,
        nfa,
        dfa,
        minDfa,
        finalRe
      };
    } catch (e: any) {
      setConverterError(e.message || 'Invalid Regular Expression');
      return null;
    }
  }, [regexInput]);

  const renderConverterGraph = () => {
    if (!conversionData) return null;

    if (mode === 'RE_TO_NFA' || mode === 'NFA_TO_DFA') {
      const isNFA = mode === 'RE_TO_NFA';
      const automaton = isNFA ? conversionData.nfa : conversionData.dfa;
      
      const nodes = automaton.states.map((s) => {
        const idStr = s.toString();
        const isStart = idStr === automaton.startState;
        const isAccept = automaton.acceptStates.includes(idStr);
          
        return {
          id: idStr,
          label: s,
          isStart,
          isAccept
        };
      });

      const edges = automaton.transitions.map((t, i) => ({
        id: i,
        from: t.from,
        to: t.to,
        label: t.label
      }));

      return <GraphView nodes={nodes} edges={edges} />;
    }

    if (mode === 'DFA_TO_RE') {
      return (
        <div style={{ display: 'flex', flexDirection: 'column', alignItems: 'center', justifyContent: 'center', height: '100%', width: '100%', padding: '2rem', textAlign: 'center' }}>
          <h2 style={{ fontSize: '1.875rem', fontWeight: 'bold', marginBottom: '1rem', color: 'var(--accent)' }}>Final Regular Expression</h2>
          <div style={{ background: 'rgba(30,41,59,0.8)', padding: '1.5rem', borderRadius: '12px', border: '1px solid var(--panel-border)', boxShadow: 'var(--glass-shadow)', fontSize: '1.5rem', fontFamily: 'monospace', color: 'var(--primary)', width: '100%', maxWidth: '42rem', wordBreak: 'break-all' }}>
            {conversionData.finalRe}
          </div>
          <p style={{ marginTop: '1.5rem', color: 'var(--text-muted)', maxWidth: '32rem' }}>
            This expression was generated by applying the State Elimination method to the DFA. It represents the same language as the original input.
          </p>
        </div>
      );
    }
  };

  const getConverterSteps = () => {
    if (!conversionData) return [];
    if (mode === 'RE_TO_NFA') {
      return [
        'Tokenized regular expression input',
        'Parsed tokens into Abstract Syntax Tree (AST)',
        "Compiled AST to ε-NFA via Thompson's construction",
        'Eliminated epsilon transitions to produce epsilon-free NFA'
      ];
    }
    if (mode === 'NFA_TO_DFA') {
      return [
        'Tokenized regular expression input',
        'Parsed tokens into AST',
        "Compiled AST to ε-NFA via Thompson's construction",
        'Eliminated epsilon transitions to produce NFA',
        'Applied subset construction to compile NFA to DFA'
      ];
    }
    return [
      'Tokenized regular expression input',
      'Parsed tokens into AST',
      "Compiled AST to ε-NFA via Thompson's construction",
      'Eliminated epsilon transitions to produce NFA',
      'Applied subset construction to compile NFA to DFA',
      'Minimized DFA using Hopcroft\'s algorithm',
      'Normalized DFA to Generalized NFA (GNFA)',
      'Eliminated states sequentially to generate equivalent regular expression'
    ];
  };

  // ==========================================
  // 2. CANVAS EDITOR STATE & LOGIC
  // ==========================================
  const [automaton, setAutomaton] = useState<Automaton>({
    type: 'DFA',
    states: ['q0'],
    alphabet: ['a', 'b'],
    transitions: [],
    startState: 'q0',
    acceptStates: []
  });

  // Editor selection state (identity-based selection for edges)
  const [selectedNode, setSelectedNode] = useState<string | null>(null);
  const [selectedEdge, setSelectedEdge] = useState<Transition | null>(null);

  // Form Inputs
  const [stateInput, setStateInput] = useState('');
  const [renameInput, setRenameInput] = useState('');
  const [transitionFrom, setTransitionFrom] = useState('q0');
  const [transitionTo, setTransitionTo] = useState('q0');
  const [transitionLabel, setTransitionLabel] = useState('');

  // Simulation State
  const [simulationInput, setSimulationInput] = useState('');
  const [simulationResult, setSimulationResult] = useState<string | null>(null);

  // Error/Status banner state
  const [editorError, setEditorError] = useState<string | null>(null);

  // Lineage parent ID tracking
  const [loadedFromItemId, setLoadedFromItemId] = useState<string | null>(null);

  // Identity-based transition selection lookup
  const currentSelectedEdge = useMemo(() => {
    if (!selectedEdge) return null;
    return automaton.transitions.find(
      t => t.from === selectedEdge.from && t.to === selectedEdge.to && t.label === selectedEdge.label
    ) || null;
  }, [selectedEdge, automaton.transitions]);

  // Graph data mapping
  const graphData = useMemo(() => {
    const nodes = automaton.states.map(s => {
      const isStart = s === automaton.startState;
      const isAccept = automaton.acceptStates.includes(s);
      return {
        id: s,
        label: s,
        isStart,
        isAccept
      };
    });

    const edges = automaton.transitions.map((t, idx) => ({
      id: idx,
      from: t.from,
      to: t.to,
      label: t.label
    }));

    return { nodes, edges };
  }, [automaton]);

  // Selection handlers
  const handleSelectNode = (nodeId: string) => {
    setSelectedNode(nodeId);
    setSelectedEdge(null);
    setRenameInput(nodeId);
  };

  const handleSelectEdge = (edgeIdx: number) => {
    const t = automaton.transitions[edgeIdx];
    if (t) {
      setSelectedEdge({ from: t.from, to: t.to, label: t.label });
    }
    setSelectedNode(null);
  };

  const handleDeselect = () => {
    setSelectedNode(null);
    setSelectedEdge(null);
  };

  // Transaction Rollback wrappers
  const handleAddState = (e: React.FormEvent) => {
    e.preventDefault();
    try {
      setEditorError(null);
      const next = applyAddState(automaton, stateInput.trim());
      setAutomaton(next);
      setStateInput('');
    } catch (err: any) {
      setEditorError(err.message || 'Failed to add state.');
    }
  };

  const handleDeleteState = () => {
    if (!selectedNode) return;
    try {
      setEditorError(null);
      const next = applyDeleteState(automaton, selectedNode);
      setAutomaton(next);
      handleDeselect();
    } catch (err: any) {
      setEditorError(err.message || 'Failed to delete state.');
    }
  };

  const handleRenameState = (e: React.FormEvent) => {
    e.preventDefault();
    if (!selectedNode) return;
    try {
      setEditorError(null);
      const next = applyRenameState(automaton, selectedNode, renameInput.trim());
      setAutomaton(next);
      handleDeselect();
    } catch (err: any) {
      setEditorError(err.message || 'Failed to rename state.');
    }
  };

  const handleAddTransition = (e: React.FormEvent) => {
    e.preventDefault();
    try {
      setEditorError(null);
      const label = transitionLabel.trim() === '' ? EPSILON : transitionLabel.trim();
      const next = applyAddTransition(automaton, transitionFrom, transitionTo, label);
      setAutomaton(next);
      setTransitionLabel('');
    } catch (err: any) {
      setEditorError(err.message || 'Failed to add transition.');
    }
  };

  const handleDeleteTransition = () => {
    if (!selectedEdge) return;
    try {
      setEditorError(null);
      const next = applyDeleteTransition(automaton, selectedEdge.from, selectedEdge.to, selectedEdge.label);
      setAutomaton(next);
      handleDeselect();
    } catch (err: any) {
      setEditorError(err.message || 'Failed to delete transition.');
    }
  };

  const handleSetStart = () => {
    if (!selectedNode) return;
    try {
      setEditorError(null);
      const next = applySetStartState(automaton, selectedNode);
      setAutomaton(next);
    } catch (err: any) {
      setEditorError(err.message || 'Failed to set start state.');
    }
  };

  const handleToggleAccept = () => {
    if (!selectedNode) return;
    try {
      setEditorError(null);
      const next = applyToggleAcceptState(automaton, selectedNode);
      setAutomaton(next);
    } catch (err: any) {
      setEditorError(err.message || 'Failed to toggle accept state.');
    }
  };

  const handleEditorSimulate = (e: React.FormEvent) => {
    e.preventDefault();
    try {
      setEditorError(null);
      let accepted = false;
      if (automaton.type === 'DFA') {
        accepted = simulateDFA(automaton, simulationInput).accepted;
      } else if (automaton.type === 'NFA') {
        accepted = simulateNFA(automaton, simulationInput).accepted;
      } else {
        accepted = simulateENFA(automaton, simulationInput).accepted;
      }
      setSimulationResult(accepted ? 'ACCEPTED' : 'REJECTED');
    } catch (err: any) {
      setSimulationResult(`ERROR: ${err.message}`);
    }
  };

  const handleSaveToWorkspace = () => {
    try {
      setEditorError(null);
      validateAutomaton(automaton);

      const newItem: WorkspaceItem = {
        id: generateUUID(),
        label: `Canvas Save (${automaton.type})`,
        parentId: loadedFromItemId,
        createdBy: 'canvasSave',
        payload: {
          kind: 'automaton',
          automaton: {
            type: automaton.type,
            states: [...automaton.states],
            alphabet: [...automaton.alphabet],
            transitions: automaton.transitions.map(t => ({ ...t })),
            startState: automaton.startState,
            acceptStates: [...automaton.acceptStates]
          }
        }
      };

      setWorkspaceItems(prev => [...prev, newItem]);
      alert('Saved current canvas to Workspace successfully!');
    } catch (err: any) {
      setEditorError(err.message || 'Failed to save canvas.');
    }
  };

  // ==========================================
  // 3. WORKSPACE REPOSITORY STATE & LOGIC
  // ==========================================
  const [workspaceItems, setWorkspaceItems] = useState<WorkspaceItem[]>([]);
  const [selectedItemAId, setSelectedItemAId] = useState<string | null>(null);
  const [selectedItemBId, setSelectedItemBId] = useState<string | null>(null);
  const [newRegexInput, setNewRegexInput] = useState('');
  const [workspaceError, setWorkspaceError] = useState<string | null>(null);
  const [equivalenceResult, setEquivalenceResult] = useState<string | null>(null);

  // Lineage action transaction wrappers (rollback contract)
  const handleAddWorkspaceRegex = (e: React.FormEvent) => {
    e.preventDefault();
    try {
      setWorkspaceError(null);
      const next = addRegexToWorkspace(workspaceItems, newRegexInput.trim());
      setWorkspaceItems(next);
      setNewRegexInput('');
    } catch (err: any) {
      setWorkspaceError(err.message || 'Failed to add regex.');
    }
  };

  const handleCompileRegex = (itemId: string) => {
    try {
      setWorkspaceError(null);
      const next = compileRegexInWorkspace(workspaceItems, itemId);
      setWorkspaceItems(next);
    } catch (err: any) {
      setWorkspaceError(err.message || 'Failed to compile regex.');
    }
  };

  const handleEliminateEpsilon = (itemId: string) => {
    try {
      setWorkspaceError(null);
      const next = eliminateEpsilonInWorkspace(workspaceItems, itemId);
      setWorkspaceItems(next);
    } catch (err: any) {
      setWorkspaceError(err.message || 'Failed to eliminate epsilon.');
    }
  };

  const handleSubsetConstruction = (itemId: string) => {
    try {
      setWorkspaceError(null);
      const next = subsetConstructionInWorkspace(workspaceItems, itemId);
      setWorkspaceItems(next);
    } catch (err: any) {
      setWorkspaceError(err.message || 'Failed subset construction.');
    }
  };

  const handleMinimize = (itemId: string) => {
    try {
      setWorkspaceError(null);
      const next = minimizeInWorkspace(workspaceItems, itemId);
      setWorkspaceItems(next);
    } catch (err: any) {
      setWorkspaceError(err.message || 'Failed to minimize DFA.');
    }
  };

  const handleGenerateRegex = (itemId: string) => {
    try {
      setWorkspaceError(null);
      const next = generateRegexInWorkspace(workspaceItems, itemId);
      setWorkspaceItems(next);
    } catch (err: any) {
      setWorkspaceError(err.message || 'Failed to generate regex.');
    }
  };

  const handleLoadIntoEditor = (item: WorkspaceItem) => {
    if (item.payload.kind === 'automaton') {
      const aut = item.payload.automaton;
      setAutomaton({
        type: aut.type,
        states: [...aut.states],
        alphabet: [...aut.alphabet],
        transitions: aut.transitions.map(t => ({ ...t })),
        startState: aut.startState,
        acceptStates: [...aut.acceptStates]
      });
      setLoadedFromItemId(item.id);
      setActiveTab('EDITOR');
      setEditorError(null);
      handleDeselect();
    }
  };

  const handleVerifyEquivalence = () => {
    if (!selectedItemAId || !selectedItemBId) return;
    const itemA = workspaceItems.find(i => i.id === selectedItemAId);
    const itemB = workspaceItems.find(i => i.id === selectedItemBId);
    if (!itemA || !itemB) return;

    try {
      setWorkspaceError(null);
      const result = compareWorkspaceItems(itemA, itemB);
      if (result.equivalent) {
        setEquivalenceResult('Equivalent: Both items accept exactly the same language.');
      } else {
        setEquivalenceResult(`Not equivalent — counterexample: "${result.counterexample}"`);
      }
    } catch (err: any) {
      setWorkspaceError(err.message || 'Comparison failed.');
      setEquivalenceResult(null);
    }
  };

  // Memoized rendering mapping for Selected Items
  const selectedItemA = useMemo(() => {
    return workspaceItems.find(i => i.id === selectedItemAId) || null;
  }, [selectedItemAId, workspaceItems]);

  const selectedItemB = useMemo(() => {
    return workspaceItems.find(i => i.id === selectedItemBId) || null;
  }, [selectedItemBId, workspaceItems]);

  // Render a workspace item visual preview
  const renderItemPreview = (item: WorkspaceItem | null, viewMode: 'graph' | 'table' = 'graph') => {
    if (!item) {
      return (
        <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'center', height: '100%', color: 'var(--text-muted)', fontStyle: 'italic' }}>
          No item selected
        </div>
      );
    }

    if (item.payload.kind === 'regex') {
      return (
        <div style={{ display: 'flex', flexDirection: 'column', alignItems: 'center', justifyContent: 'center', height: '100%', width: '100%', padding: '1rem', textAlign: 'center' }}>
          <h4 style={{ color: 'var(--accent)', margin: '0 0 1rem 0', fontSize: '1.1rem' }}>{item.label}</h4>
          <div style={{ background: 'rgba(30,41,59,0.8)', padding: '1rem', borderRadius: '8px', border: '1px solid var(--panel-border)', fontSize: '1.25rem', fontFamily: 'monospace', color: 'var(--primary)', width: '100%', maxWidth: '30rem', wordBreak: 'break-all' }}>
            {item.payload.regexString}
          </div>
        </div>
      );
    }

    const aut = item.payload.automaton;

    if (viewMode === 'table') {
      return <TransitionTable automaton={aut} />;
    }

    const nodes = aut.states.map(s => ({
      id: s,
      label: s,
      isStart: s === aut.startState,
      isAccept: aut.acceptStates.includes(s)
    }));
    const edges = aut.transitions.map((t, idx) => ({
      id: idx,
      from: t.from,
      to: t.to,
      label: t.label
    }));

    return (
      <div style={{ display: 'flex', flexDirection: 'column', height: '100%' }}>
        <div style={{ display: 'flex', justifyContent: 'space-between', padding: '0.5rem 1rem', background: 'rgba(15,23,42,0.4)', borderBottom: '1px solid var(--panel-border)', fontSize: '0.85rem' }}>
          <span>{item.label}</span>
          <span style={{ color: 'var(--accent)' }}>Type: {aut.type}</span>
        </div>
        <div style={{ flex: 1, position: 'relative' }}>
          <GraphView nodes={nodes} edges={edges} />
        </div>
      </div>
    );
  };

  return (
    <div className="app-container">
      {/* Header Tabs */}
      <header className="header glass-panel">
        <h1 className="title m-0 text-2xl" style={{ margin: 0 }}>Automata Lab</h1>
        <div style={{ display: 'flex', gap: '1rem' }}>
          <button 
            className={`btn ${activeTab === 'CONVERTER' ? 'btn-accent' : ''}`}
            onClick={() => setActiveTab('CONVERTER')}
          >
            Regex Converter
          </button>
          <button 
            className={`btn ${activeTab === 'EDITOR' ? 'btn-accent' : ''}`}
            onClick={() => setActiveTab('EDITOR')}
          >
            Canvas Editor
          </button>
          <button 
            className={`btn ${activeTab === 'WORKSPACE' ? 'btn-accent' : ''}`}
            onClick={() => setActiveTab('WORKSPACE')}
          >
            Workspace Repository
          </button>
        </div>
      </header>

      {/* RENDER CONVERTER TAB */}
      {activeTab === 'CONVERTER' && (
        <main className="main-content">
          <aside className="controls-sidebar glass-panel">
            <div>
              <h3 style={{ fontSize: '1.125rem', fontWeight: 600, marginBottom: '0.5rem', display: 'flex', alignItems: 'center', gap: '0.5rem' }}>
                <Settings size={18} /> Configuration
              </h3>
              <label style={{ display: 'block', fontSize: '0.875rem', color: 'var(--text-muted)', marginBottom: '0.25rem' }}>Regular Expression</label>
              <input
                type="text"
                className="input-field"
                value={regexInput}
                onChange={(e) => setRegexInput(e.target.value)}
                placeholder="e.g. (a|b)*abb"
              />
              {converterError && <div style={{ color: '#f87171', marginTop: '0.5rem', fontSize: '0.875rem' }}>{converterError}</div>}
            </div>

            <div style={{ display: 'flex', gap: '0.5rem', width: '100%' }}>
              <button 
                className={`btn ${mode === 'RE_TO_NFA' ? 'btn-accent' : ''}`}
                onClick={() => setMode('RE_TO_NFA')}
                style={{ flex: 1, fontSize: '0.825rem', padding: '0.5rem 0' }}
              >
                RE → NFA
              </button>
              <button 
                className={`btn ${mode === 'NFA_TO_DFA' ? 'btn-accent' : ''}`}
                onClick={() => setMode('NFA_TO_DFA')}
                style={{ flex: 1, fontSize: '0.825rem', padding: '0.5rem 0' }}
              >
                NFA → DFA
              </button>
              <button 
                className={`btn ${mode === 'DFA_TO_RE' ? 'btn-accent' : ''}`}
                onClick={() => setMode('DFA_TO_RE')}
                style={{ flex: 1, fontSize: '0.825rem', padding: '0.5rem 0' }}
              >
                DFA → RE
              </button>
            </div>

            <div className="steps-panel" style={{ background: 'rgba(30,41,59,0.5)', borderRadius: '8px', flex: 1, overflowY: 'auto' }}>
              <h3 style={{ fontSize: '1.125rem', fontWeight: 600, marginBottom: '1rem', display: 'flex', alignItems: 'center', gap: '0.5rem', color: 'var(--primary)' }}>
                <Info size={18} /> Conversion Steps
              </h3>
              <div style={{ display: 'flex', flexDirection: 'column', gap: '0.5rem' }}>
                {getConverterSteps().map((step, idx) => (
                  <div key={idx} className="step-item">
                    <span style={{ color: 'var(--accent)', fontFamily: 'monospace', marginRight: '0.5rem' }}>{idx + 1}.</span> {step}
                  </div>
                ))}
                {getConverterSteps().length === 0 && (
                  <div style={{ color: 'var(--text-muted)', fontSize: '0.875rem', fontStyle: 'italic' }}>Enter a valid regex to see steps.</div>
                )}
              </div>
            </div>
          </aside>

          <section className="visualization-area glass-panel">
            {renderConverterGraph()}
          </section>
        </main>
      )}

      {/* RENDER CANVAS EDITOR TAB */}
      {activeTab === 'EDITOR' && (
        <main className="main-content">
          <aside className="controls-sidebar glass-panel" style={{ display: 'flex', flexDirection: 'column', gap: '1.5rem' }}>
            <div>
              <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '0.75rem' }}>
                <h3 style={{ fontSize: '1.125rem', fontWeight: 600, display: 'flex', alignItems: 'center', gap: '0.5rem', margin: 0 }}>
                  <Settings size={18} /> Toolbar Panel
                </h3>
                <button onClick={handleSaveToWorkspace} className="btn btn-accent" style={{ fontSize: '0.75rem', padding: '0.25rem 0.5rem' }}>
                  Save to Workspace
                </button>
              </div>
              <div style={{ fontSize: '0.825rem', color: 'var(--text-muted)', marginBottom: '1rem' }}>
                Type: <strong>{automaton.type}</strong> {loadedFromItemId && <span style={{ color: 'var(--accent)', marginLeft: '0.5rem' }}>(Lineage Active)</span>}
              </div>
              
              {editorError && (
                <div style={{ color: '#f87171', background: 'rgba(239,68,68,0.1)', border: '1px solid rgba(239,68,68,0.2)', padding: '0.75rem', borderRadius: '6px', fontSize: '0.875rem', marginBottom: '1rem' }}>
                  {editorError}
                </div>
              )}

              {/* Form to Add State */}
              <form onSubmit={handleAddState} style={{ marginBottom: '1rem' }}>
                <label style={{ display: 'block', fontSize: '0.75rem', color: 'var(--text-muted)', marginBottom: '0.25rem' }}>Create State</label>
                <div style={{ display: 'flex', gap: '0.5rem' }}>
                  <input
                    type="text"
                    className="input-field"
                    value={stateInput}
                    onChange={(e) => setStateInput(e.target.value)}
                    placeholder="e.g. q1"
                    style={{ flex: 1 }}
                  />
                  <button type="submit" className="btn btn-accent" style={{ padding: '0.5rem' }}>
                    <Plus size={18} />
                  </button>
                </div>
              </form>

              {/* Form to Add Transition */}
              <form onSubmit={handleAddTransition} style={{ marginBottom: '1rem' }}>
                <label style={{ display: 'block', fontSize: '0.75rem', color: 'var(--text-muted)', marginBottom: '0.25rem' }}>Add Transition</label>
                <div style={{ display: 'flex', flexDirection: 'column', gap: '0.5rem' }}>
                  <div style={{ display: 'flex', gap: '0.5rem' }}>
                    <select
                      className="input-field"
                      value={transitionFrom}
                      onChange={(e) => setTransitionFrom(e.target.value)}
                      style={{ flex: 1 }}
                    >
                      {automaton.states.map(s => (
                        <option key={s} value={s}>{s}</option>
                      ))}
                    </select>
                    <span style={{ alignSelf: 'center', color: 'var(--text-muted)' }}>→</span>
                    <select
                      className="input-field"
                      value={transitionTo}
                      onChange={(e) => setTransitionTo(e.target.value)}
                      style={{ flex: 1 }}
                    >
                      {automaton.states.map(s => (
                        <option key={s} value={s}>{s}</option>
                      ))}
                    </select>
                  </div>
                  <div style={{ display: 'flex', gap: '0.5rem' }}>
                    <input
                      type="text"
                      className="input-field"
                      value={transitionLabel}
                      onChange={(e) => setTransitionLabel(e.target.value)}
                      placeholder="Symbol (empty = ε)"
                      style={{ flex: 1 }}
                    />
                    <button type="submit" className="btn btn-accent" style={{ padding: '0.5rem 1rem' }}>
                      Connect
                    </button>
                  </div>
                </div>
              </form>
            </div>

            {/* Context-aware selected actions */}
            <div style={{ background: 'rgba(30,41,59,0.5)', padding: '1rem', borderRadius: '8px', border: '1px solid var(--panel-border)' }}>
              <h4 style={{ margin: '0 0 0.75rem 0', fontSize: '0.95rem', color: 'var(--primary)' }}>Context Actions</h4>
              
              {selectedNode && (
                <div style={{ display: 'flex', flexDirection: 'column', gap: '0.75rem' }}>
                  <div style={{ fontSize: '0.875rem' }}>Selected: <strong>{selectedNode}</strong></div>
                  
                  <form onSubmit={handleRenameState} style={{ display: 'flex', gap: '0.5rem' }}>
                    <input
                      type="text"
                      className="input-field"
                      value={renameInput}
                      onChange={(e) => setRenameInput(e.target.value)}
                      style={{ flex: 1, height: '2rem', fontSize: '0.875rem' }}
                    />
                    <button type="submit" className="btn btn-accent" style={{ padding: '0.25rem 0.5rem', fontSize: '0.75rem' }}>Rename</button>
                  </form>

                  <div style={{ display: 'flex', gap: '0.5rem' }}>
                    <button onClick={handleSetStart} className="btn" style={{ flex: 1, fontSize: '0.75rem', gap: '0.25rem', padding: '0.5rem 0' }}>
                      <UserCheck size={14} /> Start
                    </button>
                    <button onClick={handleToggleAccept} className="btn" style={{ flex: 1, fontSize: '0.75rem', gap: '0.25rem', padding: '0.5rem 0' }}>
                      <ShieldCheck size={14} /> Accept
                    </button>
                  </div>

                  <button onClick={handleDeleteState} className="btn" style={{ background: 'rgba(239,68,68,0.2)', color: '#ef4444', borderColor: 'rgba(239,68,68,0.4)', fontSize: '0.75rem', gap: '0.25rem', justifyContent: 'center' }}>
                    <Trash2 size={14} /> Delete State
                  </button>
                </div>
              )}

              {currentSelectedEdge && (
                <div style={{ display: 'flex', flexDirection: 'column', gap: '0.75rem' }}>
                  <div style={{ fontSize: '0.875rem' }}>
                    Selected edge: <strong>{`${currentSelectedEdge.from} --${currentSelectedEdge.label}--> ${currentSelectedEdge.to}`}</strong>
                  </div>
                  <button onClick={handleDeleteTransition} className="btn" style={{ background: 'rgba(239,68,68,0.2)', color: '#ef4444', borderColor: 'rgba(239,68,68,0.4)', fontSize: '0.75rem', gap: '0.25rem', justifyContent: 'center' }}>
                    <Trash2 size={14} /> Delete Edge
                  </button>
                </div>
              )}

              {!selectedNode && !currentSelectedEdge && (
                <div style={{ color: 'var(--text-muted)', fontSize: '0.825rem', fontStyle: 'italic', textAlign: 'center' }}>
                  Click a state or edge in the visualization to see options.
                </div>
              )}
            </div>

            {/* Simulation Widget */}
            <div className="steps-panel" style={{ background: 'rgba(30,41,59,0.3)', borderRadius: '8px', padding: '1rem', display: 'flex', flexDirection: 'column', gap: '0.75rem' }}>
              <h3 style={{ fontSize: '1rem', fontWeight: 600, display: 'flex', alignItems: 'center', gap: '0.5rem', color: 'var(--primary)', margin: 0 }}>
                <Play size={16} /> Quick Simulator
              </h3>
              <form onSubmit={handleEditorSimulate} style={{ display: 'flex', gap: '0.5rem' }}>
                <input
                  type="text"
                  className="input-field"
                  value={simulationInput}
                  onChange={(e) => setSimulationInput(e.target.value)}
                  placeholder="Test string (e.g. ab)"
                  style={{ flex: 1 }}
                />
                <button type="submit" className="btn btn-accent" style={{ padding: '0.5rem' }}>
                  Run
                </button>
              </form>
              {simulationResult && (
                <div style={{ fontSize: '0.875rem', fontWeight: 'bold', padding: '0.5rem', borderRadius: '4px', background: 'rgba(30,41,59,0.6)', border: '1px solid var(--panel-border)', textAlign: 'center', color: simulationResult.startsWith('ERROR') ? '#f87171' : (simulationResult === 'ACCEPTED' ? '#34d399' : '#94a3b8') }}>
                  Result: {simulationResult}
                </div>
              )}
            </div>
          </aside>

          <section className="visualization-area glass-panel" style={{ display: 'flex', flexDirection: 'column' }}>
            <div style={{ padding: '0.5rem 1rem', display: 'flex', justifyContent: 'flex-end', gap: '0.5rem', background: 'rgba(15,23,42,0.4)', borderBottom: '1px solid var(--panel-border)' }}>
              <button 
                className={`btn ${editorViewMode === 'graph' ? 'btn-accent' : ''}`}
                onClick={() => setEditorViewMode('graph')}
                style={{ padding: '0.2rem 0.5rem', fontSize: '0.75rem' }}
              >
                Graph View
              </button>
              <button 
                className={`btn ${editorViewMode === 'table' ? 'btn-accent' : ''}`}
                onClick={() => setEditorViewMode('table')}
                style={{ padding: '0.2rem 0.5rem', fontSize: '0.75rem' }}
              >
                Table View
              </button>
            </div>
            <div style={{ flex: 1, position: 'relative', overflow: 'hidden' }}>
              {editorViewMode === 'graph' ? (
                <GraphView
                  nodes={graphData.nodes}
                  edges={graphData.edges}
                  onSelectNode={handleSelectNode}
                  onSelectEdge={handleSelectEdge}
                  onDeselect={handleDeselect}
                />
              ) : (
                <TransitionTable automaton={automaton} />
              )}
            </div>
          </section>
        </main>
      )}

      {/* RENDER WORKSPACE REPOSITORY TAB */}
      {activeTab === 'WORKSPACE' && (
        <main className="main-content">
          <aside className="controls-sidebar glass-panel" style={{ display: 'flex', flexDirection: 'column', gap: '1.25rem' }}>
            {/* Create Regex */}
            <div>
              <h3 style={{ fontSize: '1.1rem', fontWeight: 600, marginBottom: '0.5rem', display: 'flex', alignItems: 'center', gap: '0.5rem', color: 'var(--primary)' }}>
                <Plus size={16} /> Add Regex
              </h3>
              <form onSubmit={handleAddWorkspaceRegex} style={{ display: 'flex', gap: '0.5rem' }}>
                <input
                  type="text"
                  className="input-field"
                  value={newRegexInput}
                  onChange={(e) => setNewRegexInput(e.target.value)}
                  placeholder="e.g. (a|b)*"
                  style={{ flex: 1 }}
                />
                <button type="submit" className="btn btn-accent" style={{ padding: '0.5rem' }}>
                  Add
                </button>
              </form>
            </div>

            {/* Error alerts */}
            {workspaceError && (
              <div style={{ color: '#f87171', background: 'rgba(239,68,68,0.1)', border: '1px solid rgba(239,68,68,0.2)', padding: '0.75rem', borderRadius: '6px', fontSize: '0.825rem' }}>
                {workspaceError}
              </div>
            )}

            {/* List repository items */}
            <div style={{ flex: 1, display: 'flex', flexDirection: 'column', minHeight: 0 }}>
              <h3 style={{ fontSize: '1.1rem', fontWeight: 600, marginBottom: '0.5rem', display: 'flex', alignItems: 'center', gap: '0.5rem', color: 'var(--primary)' }}>
                <LayoutGrid size={16} /> Repository Items
              </h3>
              
              <div style={{ flex: 1, overflowY: 'auto', display: 'flex', flexDirection: 'column', gap: '0.5rem', paddingRight: '0.25rem' }}>
                {workspaceItems.map(item => {
                  const isA = item.id === selectedItemAId;
                  const isB = item.id === selectedItemBId;

                  return (
                    <div 
                      key={item.id} 
                      className="step-item" 
                      style={{ 
                        display: 'flex', 
                        flexDirection: 'column', 
                        gap: '0.5rem', 
                        padding: '0.75rem', 
                        background: (isA || isB) ? 'rgba(59,130,246,0.15)' : 'rgba(30,41,59,0.3)',
                        borderColor: isA ? '#3b82f6' : (isB ? '#10b981' : 'var(--panel-border)'),
                        borderWidth: '1px',
                        borderStyle: 'solid'
                      }}
                    >
                      <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
                        <span style={{ fontWeight: 600, fontSize: '0.85rem', wordBreak: 'break-all' }}>{item.label}</span>
                        <span style={{ fontSize: '0.7rem', color: 'var(--text-muted)' }}>{item.payload.kind.toUpperCase()}</span>
                      </div>

                      {/* Lineage Details */}
                      <div style={{ fontSize: '0.75rem', color: 'var(--text-muted)', display: 'flex', alignItems: 'center', gap: '0.25rem' }}>
                        <GitCommit size={10} /> Action: {item.createdBy}
                      </div>

                      {/* Transformation Controls */}
                      <div style={{ display: 'flex', gap: '0.25rem', flexWrap: 'wrap' }}>
                        {item.payload.kind === 'regex' && (
                          <button onClick={() => handleCompileRegex(item.id)} className="btn" style={{ padding: '0.15rem 0.3rem', fontSize: '0.7rem' }}>
                            Compile
                          </button>
                        )}
                        {item.payload.kind === 'automaton' && item.payload.automaton.type === 'ENFA' && (
                          <button onClick={() => handleEliminateEpsilon(item.id)} className="btn" style={{ padding: '0.15rem 0.3rem', fontSize: '0.7rem' }}>
                            No-Eps
                          </button>
                        )}
                        {item.payload.kind === 'automaton' && item.payload.automaton.type === 'NFA' && (
                          <button onClick={() => handleSubsetConstruction(item.id)} className="btn" style={{ padding: '0.15rem 0.3rem', fontSize: '0.7rem' }}>
                            Subset
                          </button>
                        )}
                        {item.payload.kind === 'automaton' && item.payload.automaton.type === 'DFA' && (
                          <button onClick={() => handleMinimize(item.id)} className="btn" style={{ padding: '0.15rem 0.3rem', fontSize: '0.7rem' }}>
                            Minimize
                          </button>
                        )}
                        {item.payload.kind === 'automaton' && (
                          <button onClick={() => handleGenerateRegex(item.id)} className="btn" style={{ padding: '0.15rem 0.3rem', fontSize: '0.7rem' }}>
                            Gen-RE
                          </button>
                        )}
                        {item.payload.kind === 'automaton' && (
                          <button onClick={() => handleLoadIntoEditor(item)} className="btn" style={{ padding: '0.15rem 0.3rem', fontSize: '0.7rem', color: 'var(--accent)' }}>
                            Load
                          </button>
                        )}
                      </div>

                      {/* Selection Toggle Buttons */}
                      <div style={{ display: 'flex', gap: '0.5rem', marginTop: '0.25rem' }}>
                        <button 
                          onClick={() => setSelectedItemAId(isA ? null : item.id)} 
                          className="btn" 
                          style={{ flex: 1, padding: '0.2rem', fontSize: '0.7rem', background: isA ? '#3b82f6' : 'transparent', color: isA ? '#fff' : 'var(--text)' }}
                        >
                          {isA ? 'Item A Selected' : 'Select A'}
                        </button>
                        <button 
                          onClick={() => setSelectedItemBId(isB ? null : item.id)} 
                          className="btn" 
                          style={{ flex: 1, padding: '0.2rem', fontSize: '0.7rem', background: isB ? '#10b981' : 'transparent', color: isB ? '#fff' : 'var(--text)' }}
                        >
                          {isB ? 'Item B Selected' : 'Select B'}
                        </button>
                      </div>
                    </div>
                  );
                })}

                {workspaceItems.length === 0 && (
                  <div style={{ color: 'var(--text-muted)', fontSize: '0.85rem', fontStyle: 'italic', textAlign: 'center', padding: '1rem' }}>
                    Workspace is empty. Add a regex above to begin!
                  </div>
                )}
              </div>
            </div>

            {/* Verification Widget */}
            <div className="steps-panel" style={{ background: 'rgba(30,41,59,0.3)', borderRadius: '8px', padding: '1rem', display: 'flex', flexDirection: 'column', gap: '0.5rem' }}>
              <h3 style={{ fontSize: '1rem', fontWeight: 600, display: 'flex', alignItems: 'center', gap: '0.5rem', color: 'var(--primary)', margin: 0 }}>
                <Check size={16} /> Equivalence Tester
              </h3>
              <div style={{ fontSize: '0.75rem', color: 'var(--text-muted)', lineHeight: '1.25rem' }}>
                Item A: <strong>{selectedItemA ? selectedItemA.label : 'None'}</strong><br />
                Item B: <strong>{selectedItemB ? selectedItemB.label : 'None'}</strong>
              </div>
              <button 
                onClick={handleVerifyEquivalence} 
                className="btn btn-accent" 
                disabled={!selectedItemAId || !selectedItemBId}
                style={{ width: '100%', fontSize: '0.8rem', padding: '0.4rem 0' }}
              >
                Verify Equivalence
              </button>
              {equivalenceResult && (
                <div style={{ fontSize: '0.825rem', fontWeight: 'bold', padding: '0.5rem', borderRadius: '4px', background: 'rgba(30,41,59,0.6)', border: '1px solid var(--panel-border)', textAlign: 'center', color: equivalenceResult.startsWith('Not') ? '#f87171' : '#34d399' }}>
                  {equivalenceResult}
                </div>
              )}
            </div>
          </aside>

          {/* Side by side Preview visualization panel */}
          <section className="visualization-area glass-panel" style={{ display: 'flex', flexDirection: 'column', padding: '1rem' }}>
            {/* Header bar with Graph/Table Switcher (only shown if at least one selected item is an automaton) */}
            {((selectedItemA && selectedItemA.payload.kind === 'automaton') || 
              (selectedItemB && selectedItemB.payload.kind === 'automaton')) && (
              <div style={{ display: 'flex', justifyContent: 'flex-end', gap: '0.5rem', marginBottom: '0.75rem', paddingBottom: '0.5rem', borderBottom: '1px solid var(--panel-border)' }}>
                <button 
                  className={`btn ${workspaceViewMode === 'graph' ? 'btn-accent' : ''}`}
                  onClick={() => setWorkspaceViewMode('graph')}
                  style={{ padding: '0.2rem 0.5rem', fontSize: '0.75rem' }}
                >
                  Graph View
                </button>
                <button 
                  className={`btn ${workspaceViewMode === 'table' ? 'btn-accent' : ''}`}
                  onClick={() => setWorkspaceViewMode('table')}
                  style={{ padding: '0.2rem 0.5rem', fontSize: '0.75rem' }}
                >
                  Table View
                </button>
              </div>
            )}

            <div style={{ flex: 1, display: 'grid', gridTemplateColumns: (selectedItemAId && selectedItemBId) ? '1fr 1fr' : '1fr', gap: '1rem', minHeight: 0 }}>
              {selectedItemAId && (
                <div style={{ background: 'rgba(15,23,42,0.3)', borderRadius: '12px', border: '1px solid var(--panel-border)', overflow: 'hidden', display: 'flex', flexDirection: 'column' }}>
                  <div style={{ padding: '0.5rem', background: '#3b82f6', color: '#fff', fontSize: '0.85rem', fontWeight: 'bold', textAlign: 'center' }}>
                    Item A Preview
                  </div>
                  <div style={{ flex: 1, position: 'relative', overflow: 'hidden' }}>
                    {renderItemPreview(selectedItemA, workspaceViewMode)}
                  </div>
                </div>
              )}

              {selectedItemBId && (
                <div style={{ background: 'rgba(15,23,42,0.3)', borderRadius: '12px', border: '1px solid var(--panel-border)', overflow: 'hidden', display: 'flex', flexDirection: 'column' }}>
                  <div style={{ padding: '0.5rem', background: '#10b981', color: '#fff', fontSize: '0.85rem', fontWeight: 'bold', textAlign: 'center' }}>
                    Item B Preview
                  </div>
                  <div style={{ flex: 1, position: 'relative', overflow: 'hidden' }}>
                    {renderItemPreview(selectedItemB, workspaceViewMode)}
                  </div>
                </div>
              )}

              {!selectedItemAId && !selectedItemBId && (
                <div style={{ display: 'flex', flexDirection: 'column', alignItems: 'center', justifyContent: 'center', height: '100%', color: 'var(--text-muted)', textAlign: 'center' }}>
                  <FileText size={48} style={{ strokeWidth: 1, marginBottom: '1rem' }} />
                  <h3 style={{ fontSize: '1.25rem', margin: '0 0 0.5rem 0', color: 'var(--primary)' }}>Workspace Previewer</h3>
                  <p style={{ margin: 0, fontSize: '0.875rem', maxWidth: '24rem' }}>
                    Select Item A and/or Item B in the repository list to visualize their structures side-by-side and compare language equivalence.
                  </p>
                </div>
              )}
            </div>
          </section>
        </main>
      )}
    </div>
  );
}

export default App;
